### PR TITLE
Feature/about page

### LINKED ISSUE #37: Create an About page
For introducing the product, team, etc.

### PR DESCRIPTION
**Pull request by donovanCarreno**
closes #37

### CODE REVIEW

**Comment by cassiebaer** [comment]
👾

**Comment by natgrigorovskaya** [comment]
need to fix conflicts first

**Comment by donovanCarreno** [comment]
git is scary... 👻 

doing a new PR

**Comment by cassiebaer** [comment]
closing to reopen a new PR

**Pull request closed without merging**
